main:
  - name: Bio
    url: /
    weight: 10
  - name: Books
    url: /#books
    weight: 20
  - name: Projects
    url: /#projects
    weight: 25
  - name: Training
    url: /#training
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
