// Generates the derived content artifacts from the single source data:
//   1. functions/api/_kb-data.js  — the chatbot's linkable knowledge (books,
//      repos, recent newsletter/YouTube items, each with a URL).
//   2. static/llms-full.txt       — the full agent-facing reference (= the bot's
//      brain: KNOWLEDGE_BASE + the same linkable data).
//   3. static/llms.txt            — a concise agent index per llmstxt.org.
//
// Sources (single source of truth):
//   - functions/api/_knowledge.js  (stable bio / themes / services)
//   - data/projects.json           (repos / apps / training; hand-maintained)
//   - data/recent.json             (newsletter issues + videos; written weekly by
//                                    the refresh-kb GitHub Action — may be absent)
//   - the BOOKS list below         (stable; slugs map to /publications/<slug>/)
//
// Run on demand:  node scripts/build-kb.mjs
// Also run by:    .github/workflows/refresh-kb.yml (weekly + on data changes)
// No third-party dependencies — pure Node + JSON.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { KNOWLEDGE_BASE } from "../functions/api/_knowledge.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://www.kousenit.com";

const SUMMARY =
  "Ken Kousen is a Java Champion, author of six technical books, and a trainer and speaker on Java, " +
  "Kotlin, Spring, Gradle, Android, and practical AI/LLM integration. He runs Kousen IT, Inc., teaches " +
  "at Trinity College, and publishes the weekly \"Tales from the jar side\" newsletter and YouTube channel. " +
  "Contact: ken.kousen@kousenit.com";

const BOOKS = [
  { title: "Mockito Made Clear", slug: "mockito-made-clear", note: "Mockito / testing (Pragmatic Bookshelf)" },
  { title: "Help Your Boss Help You", slug: "help-your-boss-help-you", note: "managing up for technical pros (Pragmatic Bookshelf)" },
  { title: "Kotlin Cookbook", slug: "kotlin-cookbook", note: "Kotlin recipes (O'Reilly)" },
  { title: "Modern Java Recipes", slug: "modern-java-recipes", note: "modern/functional Java (O'Reilly)" },
  { title: "Gradle Recipes for Android", slug: "gradle-recipes-for-android", note: "Gradle for Android (O'Reilly)" },
  { title: "Making Java Groovy", slug: "making-java-groovy", note: "the Groovy/Java intersection (Manning)" },
];

const LINKS = [
  ["Newsletter (Tales from the jar side)", "https://kenkousen.substack.com"],
  ["YouTube (Tales from the jar side)", "https://youtube.com/@talesfromthejarside"],
  ["Blog (Stuff I've Learned Recently)", "https://kousenit.org"],
  ["GitHub", "https://github.com/kousen"],
  ["LinkedIn", "https://www.linkedin.com/in/kenkousen/"],
  ["Bluesky", "https://bsky.app/profile/kousenit.com"],
];

const read = (p, fb) => (existsSync(join(root, p)) ? JSON.parse(readFileSync(join(root, p), "utf8")) : fb);
const projects = read("data/projects.json", { projects: [], training: [] });
const recent = read("data/recent.json", { issues: [], videos: [] });

const bookLink = (b) => `[${b.title}](${SITE}/publications/${b.slug}/)`;

// ---- 1. KB_DATA for the chatbot (terse, link-rich) ----
const kb = [];
kb.push("# Books (link to the book's page when you mention it)");
for (const b of BOOKS) kb.push(`- ${bookLink(b)} — ${b.note}`);
kb.push("", "# Projects & open-source tools (link the GitHub repo; add the live demo if present)");
for (const p of projects.projects ?? []) {
  let s = `- ${p.name}`;
  if (p.kind) s += ` (${p.kind})`;
  s += ` — ${p.description} GitHub: ${p.repo}`;
  if (p.live) s += ` · Live demo: ${p.live}`;
  kb.push(s);
}
kb.push("", "# Training materials (open-source course repos)");
for (const t of projects.training ?? []) kb.push(`- ${t.name}: ${t.description} GitHub: ${t.repo}`);
if (recent.issues?.length) {
  kb.push("", "# Recent newsletter issues (link the issue URL when relevant)");
  for (const i of recent.issues) kb.push(`- [${i.title}](${i.url})${i.date ? ` — ${i.date}` : ""}`);
}
if (recent.videos?.length) {
  kb.push("", "# Recent YouTube videos (link the video URL when relevant)");
  for (const v of recent.videos) kb.push(`- [${v.title}](${v.url})${v.date ? ` — ${v.date}` : ""}`);
}
const kbData = kb.join("\n");
writeFileSync(
  join(root, "functions/api/_kb-data.js"),
  "// AUTO-GENERATED by scripts/build-kb.mjs — do not edit by hand.\n" +
    "// Sources: data/projects.json + data/recent.json. Regenerated weekly by the\n" +
    "// refresh-kb GitHub Action, or on demand: node scripts/build-kb.mjs\n" +
    `export const KB_DATA = ${JSON.stringify(kbData)};\n`
);

// ---- 2 & 3. Agent files (llmstxt.org) ----
const idx = [];
idx.push("# Ken Kousen", "", `> ${SUMMARY}`, "");
idx.push("## Books");
for (const b of BOOKS) idx.push(`- ${bookLink(b)}: ${b.note}`);
idx.push("", "## Projects");
for (const p of projects.projects ?? []) {
  idx.push(`- [${p.name}](${p.repo}): ${p.description}${p.live ? ` (live: ${p.live})` : ""}`);
}
idx.push("", "## Training materials");
for (const t of projects.training ?? []) idx.push(`- [${t.name}](${t.repo}): ${t.description}`);
if (recent.issues?.length) {
  idx.push("", "## Recent newsletter issues");
  for (const i of recent.issues) idx.push(`- [${i.title}](${i.url})`);
}
if (recent.videos?.length) {
  idx.push("", "## Recent videos");
  for (const v of recent.videos) idx.push(`- [${v.title}](${v.url})`);
}
idx.push("", "## Links");
for (const [label, url] of LINKS) idx.push(`- [${label}](${url})`);
idx.push("");
writeFileSync(join(root, "static/llms.txt"), idx.join("\n"));

const full =
  "# Ken Kousen — full reference for AI agents\n\n" +
  `> ${SUMMARY}\n\n` +
  "This file is auto-generated from kousenit.com's data and is the same knowledge the site chatbot uses.\n\n" +
  KNOWLEDGE_BASE +
  "\n\n" +
  kbData +
  "\n";
writeFileSync(join(root, "static/llms-full.txt"), full);

console.log(
  `Generated _kb-data.js (${kbData.length} chars), static/llms.txt, static/llms-full.txt ` +
    `[${projects.projects?.length ?? 0} projects, ${projects.training?.length ?? 0} training, ` +
    `${recent.issues?.length ?? 0} issues, ${recent.videos?.length ?? 0} videos]`
);
